function [cp,ecp] = getCameraParams( theaxes )
%[cp,ecp] = getCameraParams( theaxes )
%   Get the Matlab camera parameters by reading them directly from the
%   relevant fields of THEAXES. These are:
%       CameraPosition  vector
%       CameraTarget    vector
%       CameraUpVector  vector
%       CameraViewAngle scalar, in degrees.
%       Projection      string, either 'orthographic' or 'perspective'
%
%ecp returns all the other camera-relevant properties:
%     CameraPositionMode
%     CameraTargetMode
%     CameraUpVectorMode
%     CameraViewAngleMode
%     DataAspectRatio
%     DataAspectRatioMode
%     PlotBoxAspectRatio
%     PlotBoxAspectRatioMode

    cp = struct( ...
        'CameraPosition', get( theaxes,'CameraPosition' ), ...
        'CameraTarget', get( theaxes,'CameraTarget' ), ...
        'CameraUpVector', get( theaxes,'CameraUpVector' ), ...
        'CameraViewAngle', get( theaxes,'CameraViewAngle' ), ...
        'Projection', get( theaxes,'Projection' ) );
    ecp = struct( ...
        'CameraPositionMode', get( theaxes,'CameraPositionMode' ), ...
        'CameraTargetMode', get( theaxes,'CameraTargetMode' ), ...
        'CameraUpVectorMode', get( theaxes,'CameraUpVectorMode' ), ...
        'CameraViewAngleMode', get( theaxes,'CameraViewAngleMode' ), ...
        'DataAspectRatio', get( theaxes,'DataAspectRatio' ), ...
        'DataAspectRatioMode', get( theaxes,'DataAspectRatioMode' ), ...
        'PlotBoxAspectRatio', get( theaxes,'PlotBoxAspectRatio' ), ...
        'PlotBoxAspectRatioMode', get( theaxes,'PlotBoxAspectRatioMode' ) );
end
