function setCameraParams( theaxes, cp )
    if any(isnan(cp.CameraPosition))
        cp.CameraPosition = [40 0 0];
    end
    if any(isnan(cp.CameraTarget))
        cp.CameraTarget = [0 0 0];
    end
    if any(isnan(cp.CameraUpVector))
        cp.CameraUpVector = [0 0 1];
    end
    if any(isnan(cp.CameraViewAngle))
        cp.CameraViewAngle = 10;
    end
    
    set( theaxes, ...
        'CameraPosition', cp.CameraPosition, ...
        'CameraTarget', cp.CameraTarget, ...
        'CameraUpVector', cp.CameraUpVector, ...
        'CameraViewAngle', cp.CameraViewAngle, ...
        ... % 'Projection', cp.Projection, ...
        'CameraPositionMode', 'manual', ...
        'CameraTargetMode', 'manual', ...
        'CameraUpVectorMode', 'manual', ...
        'CameraViewAngleMode', 'manual', ...
        'DataAspectRatio', [1 1 1], ...
        'DataAspectRatioMode', 'manual', ...
        'PlotBoxAspectRatio',[1 1 1], ...
        'PlotBoxAspectRatioMode', 'manual' );
    setCamlight( theaxes );
end
