function setCameraParams( theaxes, cp )
    set( theaxes, ...
        'CameraPosition', cp.CameraPosition, ...
        'CameraTarget', cp.CameraTarget, ...
        'CameraUpVector', cp.CameraUpVector, ...
        'CameraViewAngle', cp.CameraViewAngle, ...
        ... % 'Projection', cp.Projection, ...
        'CameraPositionMode', 'manual', ...
        'CameraTargetMode', 'manual', ...
        'CameraUpVectorMode', 'manual', ...
        'CameraViewAngleMode', 'manual', ...
        'DataAspectRatio', [1 1 1], ...
        'DataAspectRatioMode', 'manual', ...
        'PlotBoxAspectRatio',[1 1 1], ...
        'PlotBoxAspectRatioMode', 'manual' );
    setCamlight( theaxes );
end
