function h = plotmsr( ax, msr )
%h = plotmsr( ax, msr )
%   Plot an MSR structure as generated by msrfilereader.
%   For each object in the cell array msr.OBJECT, the vertexes, edges, and
%   faces will be plotted.  Edges and faces need not be present.
%   Currently, no options have been provided for specifying colours, vertex
%   sizes, line thicknesses, etc.  Labels in the MSR file are ignored.
%   Faces are filled in cyan, edges of faces are in red, and edges wwithout
%   faces are black dashed lines.

    if ishandle(ax)
        if strcmp( get(ax,'Type'), 'figure' )
            ax = axes('Parent',ax);
        elseif ~strcmp( get(ax,'Type'), 'axes' )
            error( 'Invalid handle supplied to %s.', mfilename() );
            return;
        end
    end
    if ~ishandle(ax)
        msr = ax;
        ax = gca();
    end
    if ischar(msr)
        msr = msrfilereader( msr );
    end
    if ~isstruct(msr) || ~isfield( msr, 'MSR_VERSION' )
        error( 'Invalid MSR structure supplied to %s.', mfilename() );
        return;
    end
    
    if ~isfield( msr, 'OBJECT' )
        return;
    end
    
    for i=1:length(msr.OBJECT)
        ob = msr.OBJECT{i};
        vxs = ob.VERT;
        if isfield( ob, 'FACE' )
            faces = ob.FACE;
            % plot the faces
            patch( 'Parent', ax, 'Vertices', vxs, 'Faces', faces, 'FaceColor', 'c', 'EdgeColor', 'r' );
        end
        if isfield( ob, 'EDGE' )
            edges = ob.EDGE;
            % plot the edges
            edgevxs = reshape( vxs(edges',:), size(edges,2), [], size(vxs,2) );
            if size(vxs,2)==2
                line( edgevxs(:,:,1), edgevxs(:,:,2), 'Parent', ax, 'Color', 'k', 'LineStyle', '--' );
            else
                line( edgevxs(:,:,1), edgevxs(:,:,2), edgevxs(:,:,3), 'Parent', ax, 'Color', 'k', 'LineStyle', '--' );
            end
        end
        % plot the vertexes
        oldhold = get( ax, 'NextPlot' );
        hold(ax,'on');
        plotpts( ax, vxs, 'LineStyle', 'none', 'MarkerSize', 10, 'Marker', 'o' );
        % patch( 'Parent', ax, 'Vertices', vxs, 'LineStyle', 'none', 'FaceColor', 'none', 'EdgeColor', 'none', 'MarkerSize', 10, 'Marker', 'o' );
        set(ax,'NextPlot',oldhold);
    end
end
