function createMeshParamInfo()
% mkparams( internal name, user name, default value, x, y )

    global MESH_PARAMS;
    global MESH_MENUNAMES;

    MESH_PARAMS = struct();
    MESH_PARAMS.circle = struct( ...
        'menuname', 'Circle', ...
        'xwidth',    mkparams( 'X wd.',  2, 1, 1, deescape( 'Diameter in X direction.' ) ), ...
        'ywidth',    mkparams( 'Y wd.',  2, 1, 2, deescape( 'Diameter in Y direction.' ) ), ...
        'circumpts', mkparams( 'Circum', 0, 2, 1, deescape( 'Number of divisions\naround the circumference.' ) ), ...
        'asym',      mkparams( 'Asym',   0, 2, 2, deescape( 'Asymmetry along X axis (-1..1).' ) ), ...
        'rings',     mkparams( 'Rings',  4, 3, 1, deescape( 'Number of rings of\nfinite elements.' ) ), ...
        'innerpts',  mkparams( 'Inner',  0, 3, 2, deescape( 'Number of elements in\nthe innermost ring.' ) ), ...
        'hollow',    mkparams( 'Hollow', 0, 3, 3, deescape( 'Hollowness [0..1).' ) ), ...
        'dealign',   mkparams( '',       0, 0, 0, '' ), ...
        'height',    mkparams( '',       0, 0, 0, deescape( 'Generate a circle or hemispherical surface.' ) ) ...
        );

    MESH_PARAMS.semicircle = struct( ...
        'menuname', 'Semicircle', ...
        'xwidth',    mkparams( 'X wd.',  2, 1, 1, deescape( 'Diameter in X direction.' ) ), ...
        'ywidth',    mkparams( 'Y wd.',  2, 1, 2, deescape( 'Diameter in Y direction.' ) ), ...
        'circumpts', mkparams( 'Circum', 0, 2, 1, deescape( 'Number of divisions\naround the circumference.' ) ), ...
        'asym',      mkparams( 'Asym',   0, 2, 2, deescape( 'Asymmetry along X axis (-1..1).' ) ), ...
        'rings',     mkparams( 'Rings',  4, 3, 1, deescape( 'Number of rings of\nfinite elements.' ) ), ...
        'innerpts',  mkparams( 'Inner',  0, 3, 2, deescape( 'Number of elements in\nthe innermost ring.' ) ), ...
        'hollow',    mkparams( 'Hollow', 0, 3, 3, deescape( 'Hollowness [0..1).' ) ), ...
        'dealign',   mkparams( '',       0, 0, 0, '' ), ...
        'height',    mkparams( '',       0, 0, 0, deescape( 'Generate a semicircle or quarter-spherical surface.' ) ) ...
        );

    MESH_PARAMS.hemisphere = struct( ...
        'menuname', 'Hemisphere', ...
        'constructor', 'circle', ...
        'xwidth',    mkparams( 'X wd.',  2, 1, 1, deescape( 'Diameter in X direction.' ) ), ...
        'ywidth',    mkparams( 'Y wd.',  2, 1, 2, deescape( 'Diameter in Y direction.' ) ), ...
        'circumpts', mkparams( 'Circum', 0, 2, 1, deescape( 'Number of divisions\naround the circumference.' ) ), ...
        'height',    mkparams( 'Height', 1, 2, 2, deescape( 'Height of hemisphere as a proportion of base radius.' ) ), ...
        'rings',     mkparams( 'Rings',  4, 3, 1, deescape( 'Number of rings of\nfinite elements.' ) ), ...
        'innerpts',  mkparams( 'Inner',  0, 3, 2, deescape( 'Number of elements in\nthe innermost ring.' ) ), ...
        'dealign',   mkparams( '',       0, 0, 0, '' ) ...
        );

    MESH_PARAMS.lobes = struct( ...
        'menuname', 'Lobes', ...
        'radius', mkparams( 'Radius', 2, 1, 1, deescape( 'Radius of lobes.' ) ), ...
        'rings', mkparams( 'Rings', 3, 1, 2, deescape( 'Number of rings of finite\nelements in each lobe.' ) ), ...
        'height', mkparams( 'Height', 0.3, 2, 1, deescape( 'Height of the rectangular\npart of each lobe' ) ), ...
        'strips', mkparams( 'Strips', 0, 2, 2, deescape( 'Number of strips of finite elements the\nrectangular part is divided into.' ) ), ...
        'lobes', mkparams( 'Lobes', 2, 3, 1, deescape( 'Number of lobes.' ) ), ...
        'base', mkparams( 'Base', 0, 3, 2, '' ), ...
        'circumference', mkparams( 'Circum', 0, 1, 3, deescape( 'Circumferential elements in the semicircular part.' ) ), ...
        'innercircumference', mkparams( 'Incirc', 0, 2, 3, deescape( 'Elements in the innermost ring of the semicircular part.' ) ), ...
        'cylinder', mkparams( '', 0, 0, 0, '' ) ...
        );

    MESH_PARAMS.lune = struct( ...
        'menuname', 'Lune', ...
        'xwidth', mkparams( 'X wd.', 4, 1, 1, '' ), ...
        'ywidth', mkparams( 'Y wd.', 4, 1, 2, '' ), ...
        'xdivs', mkparams( 'X divs', 4, 2, 1, '' ) ...
        );

    MESH_PARAMS.rectangle = struct( ...
        'menuname', 'Rectangle', ...
        'xwidth', mkparams( 'X wid.', 2, 1, 1, deescape( 'Width in the X direction.' ) ), ...
        'ywidth', mkparams( 'Y wid.', 2, 1, 2, deescape( 'Width in the Y direction.' ) ), ...
        'xdivs', mkparams( 'X divs', 4, 2, 1, deescape( 'Number of finite elements\nin the X direction.' ) ), ...
        'ydivs', mkparams( 'Y divs', 4, 2, 2, deescape( 'Number of finite elements\nin the Y direction.' ) ), ...
        'base', mkparams( 'Base', 0, 3, 2, deescape( 'Number of FEs in the X direction\nalong the side of minimum Y.' ) ) ...
        );

    MESH_PARAMS.box = struct( ...
        'menuname',    'Box', ...
        'xwidth',      mkparams( 'X wd.',  2, 1, 1, deescape( 'Diameter in X direction.' ) ), ...
        'ywidth',      mkparams( 'Y wd.',  2, 1, 2, deescape( 'Diameter in Y direction.' ) ), ...
        'zwidth',      mkparams( 'Z wd.',  2, 1, 3, deescape( 'Diameter in Z direction.' ) ), ...
        'xdivs',       mkparams( 'X divs',  4, 2, 1, deescape( 'Number of divisions\nin X direction.' ) ), ...
        'ydivs',       mkparams( 'Y divs',  4, 2, 2, deescape( 'Number of divisions\nin Y direction.' ) ), ...
        'zdivs',       mkparams( 'Z divs',  4, 2, 3, deescape( 'Number of divisions\nin Z direction.' ) ), ...
        'edgeradius',  mkparams( 'Edge',  2, 3, 1, deescape( 'Edge radius.' ) ) ...
        );

    MESH_PARAMS.oneelement = struct( ...
        'menuname', 'One element', ...
        'constructor', 'onecell', ...
        'xwidth', mkparams( 'X wid.', 2, 1, 1, deescape( 'Width in the X direction.' ) ), ...
        'ywidth', mkparams( 'Y wid.', sqrt(3), 1, 2, deescape( 'Width in the Y direction.' ) ) ...
        );

    MESH_PARAMS.cylinder = struct( ...
        'menuname', 'Cylinder', ...
        'xwidth', mkparams( 'X wd.', 2, 1, 1, deescape( 'Diameter of the cylinder in the X direction.' ) ), ...
        'ywidth', mkparams( 'Y wd.', 2, 1, 2, deescape( 'Diameter of the cylinder in the Y direction.' ) ), ...
        'circumdivs', mkparams( 'N round', 12, 2, 1, deescape( 'Number of FEs around.' ) ), ...
        'height', mkparams( 'Height', 2, 3, 1, deescape( 'Height of the cylinder.' ) ), ...
        'heightdivs', mkparams( 'N up', 4, 3, 2, deescape( 'Number of FEs tall.' ) ), ...
        'basecap', mkparams( '', 0, 0, 0, '' ), ...
        'topcap', mkparams( '', 0, 0, 0, '' ) ...
        );

    MESH_PARAMS.cup = struct( ...
        'menuname', 'Cup', ...
        'constructor', 'cylinder', ...
        'xwidth', mkparams( 'X wd.', 2, 1, 1, deescape( 'Diameter of the cylinder in the X direction.' ) ), ...
        'ywidth', mkparams( 'Y wd.', 2, 1, 2, deescape( 'Diameter of the cylinder in the Y direction.' ) ), ...
        'height', mkparams( 'Height', 2, 1, 3, deescape( 'Height of the cylindrical part.' ) ), ...
        'circumdivs', mkparams( 'N round', 12, 2, 1, deescape( 'Number of FEs around.' ) ), ...
        'baseheight', mkparams( 'Base ht', 1, 2, 3, deescape( 'Height of the base cap as\na proportion of radius.' ) ), ...
        'heightdivs', mkparams( 'N up', 4, 3, 1, deescape( 'Number of FEs tall.' ) ), ...
        'baserings', mkparams( 'Base rg', 0, 3, 3, deescape( 'Number of rings of FEs\nin the base cap.' ) ), ...
        'basecap', mkparams( '', 1, 0, 0, '' ), ...
        'topcap', mkparams( '', 0, 0, 0, '' ) ...
        );

    MESH_PARAMS.cap = struct( ...
        'menuname', 'Cap', ...
        'constructor', 'cylinder', ...
        'xwidth', mkparams( 'X wd.', 2, 1, 1, deescape( 'Diameter of the cylinder in the X direction.' ) ), ...
        'ywidth', mkparams( 'Y wd.', 2, 1, 2, deescape( 'Diameter of the cylinder in the Y direction.' ) ), ...
        'height', mkparams( 'Height', 2, 1, 3, deescape( 'Height of the cylindrical part.' ) ), ...
        'circumdivs', mkparams( 'N round', 12, 2, 1, deescape( 'Number of FEs around.' ) ), ...
        'topheight', mkparams( 'Top ht', 1, 2, 2, deescape( 'Height of the top cap as\na proportion of radius.' ) ), ...
        'heightdivs', mkparams( 'N up', 4, 3, 1, deescape( 'Number of FEs tall.' ) ), ...
        'toprings', mkparams( 'Top rg', 0, 3, 2, deescape( 'Number of rings of FEs\nin the top cap.' ) ), ...
        'basecap', mkparams( '', 0, 0, 0, '' ), ...
        'topcap', mkparams( '', 1, 0, 0, '' ) ...
        );

    MESH_PARAMS.capsule = struct( ...
        'menuname', 'Capsule', ...
        'constructor', 'cylinder', ...
        'xwidth', mkparams( 'X wd.', 2, 1, 1, deescape( 'Diameter of the cylinder in the X direction.' ) ), ...
        'ywidth', mkparams( 'Y wd.', 2, 1, 2, deescape( 'Diameter of the cylinder in the Y direction.' ) ), ...
        'height', mkparams( 'Height', 2, 1, 3, deescape( 'Height of the cylindrical part.' ) ), ...
        'circumdivs', mkparams( 'N round', 12, 2, 1, deescape( 'Number of FEs around.' ) ), ...
        'topheight', mkparams( 'Top ht', 1, 2, 2, deescape( 'Height of the top cap as\na proportion of radius.' ) ), ...
        'baseheight', mkparams( 'Base ht', 1, 2, 3, deescape( 'Height of the base cap as\na proportion of radius.' ) ), ...
        'heightdivs', mkparams( 'N up', 4, 3, 1, deescape( 'Number of FEs tall.' ) ), ...
        'toprings', mkparams( 'Top rg', 0, 3, 2, deescape( 'Number of rings of FEs\nin the top cap.' ) ), ...
        'baserings', mkparams( 'Base rg', 0, 3, 3, deescape( 'Number of rings of FEs\nin the base cap.' ) ), ...
        'basecap', mkparams( '', 1, 0, 0, '' ), ...
        'topcap', mkparams( '', 1, 0, 0, '' ) ...
        );

    MESH_PARAMS.snapdragon = struct( ...
        'menuname', 'Snapdragon', ...
        'radius', mkparams( 'Radius', 2, 1, 1, deescape( 'Radius of the cylindrical\npart of the snapdragon.' ) ), ...
        'rings', mkparams( 'Rings', 2, 1, 2, deescape( 'Number of rings of FEs in each lobe.' ) ), ...
        'bowl', mkparams( 'Bowl', 0.5, 1, 3, deescape( 'Depth of the hemispherical base\ncap as a proportion of radius.' ) ), ...
        'height', mkparams( 'Height', 0.3, 2, 1, deescape( 'Height of the cylindrical part.' ) ), ...
        'strips', mkparams( 'Strips', 0, 2, 2, deescape( 'Number of horizontal strips of\nFEs in the cylindrical part.' ) ), ...
        'baserings', mkparams( 'BowlRg', 0, 2, 3, deescape( 'Number of rings of FEs in the base cap.' ) ), ...
        'petals', mkparams( 'Petals', 5, 3, 1, deescape( 'Number of lobes.' ) ), ...
        'base', mkparams( 'Base', 0, 3, 2, deescape( 'Number of FEs around the circumference\nof the base, per half-lobe.' ) ) ...
        );

    MESH_PARAMS.icosahedron = struct( ...
        'menuname', 'Icosahedron', ...
        'radius', mkparams( 'Radius', 1, 1, 1, deescape( 'Radius of the icosahedron.' ) ), ...
        'refinement', mkparams( 'Refinement', 0, 1, 2, deescape( 'Refinement of the icosahedron.' ) ) ...
        );

    MESH_PARAMS.block3d = struct( ...
        'menuname', 'Block 3D', ...
        'constructor', 'block3D', ...
        'xwidth', mkparams( 'X wid.', 2, 1, 1, deescape( 'Width in the X direction.' ) ), ...
        'ywidth', mkparams( 'Y wid.', 2, 1, 2, deescape( 'Width in the Y direction.' ) ), ...
        'zwidth', mkparams( 'Z wid.', 2, 1, 3, deescape( 'Width in the Z direction.' ) ), ...
        'xdivs', mkparams( 'X divs', 4, 2, 1, deescape( 'Number of finite elements\nin the X direction.' ) ), ...
        'ydivs', mkparams( 'Y divs', 4, 2, 2, deescape( 'Number of finite elements\nin the Y direction.' ) ), ...
        'zdivs', mkparams( 'Z divs', 4, 2, 3, deescape( 'Number of finite elements\nin the Z direction.' ) ) ...
        );

    MESH_PARAMS.cylinder3d = struct( ...
        'menuname', 'Cylinder 3D', ...
        'constructor', 'cylinder3D', ...
        'xwidth', mkparams( 'X wid.', 2, 1, 1, deescape( 'Width in the X direction.' ) ), ...
        'ywidth', mkparams( 'Y wid.', 2, 1, 2, deescape( 'Width in the Y direction.' ) ), ...
        'zwidth', mkparams( 'Z wid.', 1, 1, 3, deescape( 'Width in the Z direction.' ) ), ...
        'rings', mkparams( 'Rings', 4, 2, 1, deescape( 'Number of concentric cylinders.' ) ), ...
        'axisdivs', mkparams( 'Axis', 4, 2, 2, deescape( 'Number of layers\nin the Z direction.' ) ), ...
        'circumdivs', mkparams( 'Circum', 4, 2, 3, deescape( 'Number of finite elements\naround the outside.' ) ) ...
        );

    MESH_PARAMS.sphere3dico = struct( ...
        'menuname', 'Sphere 3D (Ico)', ...
        'constructor', 'sphere3D', ...
        'xwidth', mkparams( 'X wid.', 2, 1, 1, deescape( 'Width in the X direction.' ) ), ...
        'ywidth', mkparams( 'Y wid.', 2, 1, 2, deescape( 'Width in the Y direction.' ) ), ...
        'zwidth', mkparams( 'Z wid.', 2, 1, 3, deescape( 'Width in the Z direction.' ) ), ...
        'shells', mkparams( 'Shells', 4, 2, 1, deescape( 'Number of shells of finite elements.' ) ), ...
        'hollow', mkparams( 'Hollow', 0, 2, 2, deescape( 'Relative radius of hollow interior.' ) ), ...
        'segments', mkparams( 'Segments', 20, 2, 3, deescape( 'Number of triangular segments (8 or 20).' ) ) ...
        );

    MESH_PARAMS.sphere3doct = struct( ...
        'menuname', 'Sphere 3D (Oct)', ...
        'constructor', 'sphere3D', ...
        'xwidth', mkparams( 'X wid.', 2, 1, 1, deescape( 'Width in the X direction.' ) ), ...
        'ywidth', mkparams( 'Y wid.', 2, 1, 2, deescape( 'Width in the Y direction.' ) ), ...
        'zwidth', mkparams( 'Z wid.', 2, 1, 3, deescape( 'Width in the Z direction.' ) ), ...
        'shells', mkparams( 'Shells', 4, 2, 1, deescape( 'Number of shells of finite elements.' ) ), ...
        'hollow', mkparams( 'Hollow', 0, 2, 2, deescape( 'Relative radius of hollow interior.' ) ), ...
        'segments', mkparams( 'Segments', 8, 2, 3, deescape( 'Number of triangular segments (8 or 20).' ) ) ...
        );

    MESH_PARAMS.hemisphere3d = struct( ...
        'menuname', 'Hemisphere 3D', ...
        'constructor', 'sphere3D', ...
        'xwidth', mkparams( 'X wid.', 2, 1, 1, deescape( 'Width in the X direction.' ) ), ...
        'ywidth', mkparams( 'Y wid.', 2, 1, 2, deescape( 'Width in the Y direction.' ) ), ...
        'zwidth', mkparams( 'Z wid.', 2, 1, 3, deescape( 'Width in the Z direction.' ) ), ...
        'shells', mkparams( 'Shells', 4, 2, 1, deescape( 'Number of shells of finite elements.' ) ), ...
        'segments', mkparams( 'Segments', 8, 2, 2, deescape( 'Number of triangular segments (8 or 20).' ) ), ...
        'otherparams', struct( 'hemisphere', true ) ...
        );
    
    fns = fieldnames( MESH_PARAMS );
    MESH_MENUNAMES = {};
    for i=1:length(fns)
        fn = fns{i};
        MESH_MENUNAMES{end+1} = MESH_PARAMS.(fn).menuname;
    end
end

function p = mkparams( name, dft, row, col, tooltip )
    p = struct( 'guiname', name, ...
                'default', dft, ...
                'row', row, ...
                'col', col, ...
                'tooltip', tooltip );
end

