function wp = emptyWaypoint()
    wp = struct( ...
        'name', '', ...
        'numframes', 0, ...
        'simtime', 0, ...
        'timestep', 1, ...
        'spins', 0, ...
        'tilts', 0, ...
        'tiltangle', 60, ...
        'crossfade', true, ...
        'framespergyration', 60, ...
        'plotoptions', struct() );
end
