function s = emptySelection()
    s = struct( ...
            'clickedCell', 0, ...
            'clickedEdge', 0, ...
            'clickedVx', 0, ...
            'highlightedCellList', [], ...
            'highlightedEdgeList', [], ...
            'highlightedVxList', [] ...
        );
end
