function a = feAngle( m, ci, cei )
%a = feAngle( m, ci, cei )
%   Compute one angle of the finite element ci.

    a = triangleAngle( ...
            m.nodes( ...
                m.tricellvxs( ci, ...
                              [cei,mod(cei,3)+1,mod(cei+1,3)+1] ), ...
                : ...
            ) ...
        );
end
