function fixedmode = getFixedMode( handles )
    fixedmode = struct( 'x', get( handles.fixXbox, 'Value' ), ...
                        'y', get( handles.fixYbox, 'Value' ), ...
                        'z', get( handles.fixZbox, 'Value' ) );
end
