function t = initTubules()
    global gMTProperties
    
    for i=1:length(gMTProperties)
        tubuleparams.(gMTProperties{i}) = 0;
    end
    
    emptytrack = newemptystreamline();
    
    t = struct( ...
            'tracks', emptystructarray( emptytrack ), ...
            'maxid', 0, ...
            'defaulttrack', emptytrack, ...
            'tubuleparams', tubuleparams, ...
            'statistics', struct( ...
                ... % 'created', 0, ...
                'deleted', 0, ...
                'died', 0, ...
                ... % 'edgecatastrophe', 0, ...
                'edgecatastropheinfo', zeros(0,5), ...
                ... % 'spontaneouscatastrophe', 0, ...
                'spontaneouscatastropheinfo', zeros(0,5), ...
                ... % 'spontaneousstop', 0, ...
                'spontstopinfo', zeros(0,5), ...
                ... % 'zipperings', 0, ...
                'zipinfo', zeros(0,5), ...
                ... % 'spontbranchings', 0, ...
                'spontbranchinfo', zeros(0,5), ...
                ... % 'xoverbranchings', 0, ...
                'xoverbranchinfo', zeros(0,5), ...
                ... % 'crossovers', 0, ...
                'crossoverinfo', zeros(0,5), ...
                ... % 'collidecatastrophe', 0, ...
                'collidecatastropheinfo', zeros(0,5), ...
                ... % 'colliderbranch', 0, ... % Obsolete? Counts events when the collision happens, not when the pending event happens.
                ... % 'collidercut', 0, ... % Obsolete? Counts events when the collision happens, not when the pending event happens.
                ... % 'collidedcut', 0, ... % Obsolete? Counts events when the collision happens, not when the pending event happens.
                ... % 'collidestop', 0, ... % Obsolete. Never used.
                ... % 'rescue', 0, ...
                'rescueinfo', zeros(0,5), ...
                ... % 'severings', 0, ...
                'severinginfo', zeros(0,5), ...
                'lifetimes', zeros(0,2), ...
                ...
                ... % The following are for backward compatability with some old models.
                'created', 0, ...
                'severings', 0, ...
                'outcomeangle', zeros(1,3), ...
                'outcomecross', zeros(1,4) ) ...
            );
end
