function t = initTubules()
    global gMTProperties
    
    for i=1:length(gMTProperties)
        tubuleparams.(gMTProperties{i}) = 0;
    end
    tubuleparams.linecolormap = [ 0 0 1 ];
    tubuleparams.plus_catastrophe_scaling = 1;
    tubuleparams.prob_branch_scaling = 1;
    tubuleparams.density_branch_scaling = 1;
    
    emptytrack = newemptystreamline();
    statsWidth = 6;
    
    t = struct( ...
            'tracks', emptystructarray( emptytrack ), ...
            'maxid', 0, ...
            'defaulttrack', emptytrack, ...
            'tubuleparams', tubuleparams, ...
            'statistics', struct( ...
                'deleted', 0, ...
                'died', 0, ...
                'edgecatastropheinfo', zeros(0,statsWidth), ...
                'spontaneouscatastropheinfo', zeros(0,statsWidth), ...
                'spontstopinfo', zeros(0,statsWidth), ...
                'zipinfo', zeros(0,statsWidth), ...
                'spontbranchinfo', zeros(0,statsWidth), ...
                'xoverbranchinfo', zeros(0,statsWidth), ...
                'crossoverinfo', zeros(0,statsWidth), ...
                'collidecatastropheinfo', zeros(0,statsWidth), ...
                'rescueinfo', zeros(0,statsWidth), ...
                'creationinfo', zeros(0,statsWidth), ...
                'severinginfo', zeros(0,statsWidth), ...
                'lifetimes', zeros(0,2), ...
                ...
                ... % The following are for backward compatability with some old models.
                'created', 0, ...
                'severings', 0, ...
                'outcomeangle', zeros(1,3), ...
                'outcomecross', zeros(1,4) ) ...
            );
end
