function t = initTubules()
    global gMTProperties
    
    % Initialise all tubule parameters to zero.
    for i=1:length(gMTProperties)
        tubuleparams.(gMTProperties{i}) = 0;
    end
    % For most parameters, the value that "does nothing" is zero. Here
    % follow the exceptions:
    tubuleparams.linecolormap = [ 0 0 1 ]; % This must be an rgb triple.
    tubuleparams.mt_max_density = Inf; % Inf = no cap on density.
    tubuleparams.plus_catastrophe_scaling = 1; % Scaling by 1 = no effect.
    tubuleparams.prob_free_branch_scaling = 1; % Scaling by 1 = no effect.
    tubuleparams.prob_xover_branch_scaling = 1; % Scaling by 1 = no effect.
    tubuleparams.density_branch_scaling = 1; % Scaling by 1 = no effect.
    tubuleparams.max_rescue_scaling = Inf; % No cap on how far rescue rate can be scaled up.
    tubuleparams.SCALE_CURVATURE_CAT_BY_DENSITY = false; % This is a boolean, not a number.
    
    emptytrack = newemptystreamline();
    statsWidth = 6;
    
    t = struct( ...
            'tracks', emptystructarray( emptytrack ), ...
            'maxid', 0, ...
            'defaulttrack', emptytrack, ...
            'tubuleparams', tubuleparams, ...
            'statistics', struct( ...
                'deleted', 0, ...
                'died', 0, ...
                'edgecatastropheinfo', zeros(0,statsWidth), ...
                'spontaneouscatastropheinfo', zeros(0,statsWidth), ...
                'spontstopinfo', zeros(0,statsWidth), ...
                'zipinfo', zeros(0,statsWidth), ...
                'spontbranchinfo', zeros(0,statsWidth), ...
                'xoverbranchinfo', zeros(0,statsWidth), ...
                'crossoverinfo', zeros(0,statsWidth), ...
                'collidecatastropheinfo', zeros(0,statsWidth), ...
                'rescueinfo', zeros(0,statsWidth), ...
                'creationinfo', zeros(0,statsWidth), ...
                'severinginfo', zeros(0,statsWidth), ...
                'lifetimes', zeros(0,2), ...
                ...
                ... % The following are for backward compatability with some old models.
                'created', 0, ...
                'severings', 0, ...
                'outcomeangle', zeros(1,3), ...
                'outcomecross', zeros(1,4) ) ...
            );
end
