function isint = isinteractive( m )
%isint = isinteractive( m )
%   Determine if m is being processed interactively from within GFtbox.
%   This is deemed to be true if m.pictures is nonempty, m.pictures(1) is a
%   figure handle, and its tag is 'GFTwindow'.

    isint = (~isempty( m )) ...
            && isfield( m, 'pictures' ) ...
            && (~isempty( m.pictures )) ...
            && ishghandle( m.pictures(1) ) ...
            && strcmp( get( ancestor( m.pictures(1), 'figure' ), 'Tag' ), 'GFTwindow' );
end
