function isint = isinteractive( m )
%isint = isinteractive( m )
%   Determine if m is being processed interactively from within GFtbox.
%   WARNIng: This is not actually a definitive, ground-truth test.

    isint = (~isempty( m )) ...
            ... % && (~oncluster()) ...
            && isfield( m, 'pictures' ) ...
            && (~isempty( m.pictures )) ...
            && ishghandle( m.pictures(1) ) ...
            && strcmp( get( ancestor( m.pictures(1), 'figure' ), 'Tag' ), 'GFTwindow' );
end
