function [ cells, bcs ] = meshGlobalToBaryCoords( m, gc, hint, normalise )
    if nargin < 3, hint = []; end
    [ cells, bcs ] = globalToBaryCoords( ...
        gc, ...
        m.nodes, ...
        m.tricellvxs, ...
        m.unitcellnormals, ...
        hint );
    bcs = normaliseBaryCoords( bcs );
end
