function c = multicolourmgens( m, mgens, multibrighten, mgenbound )
%
%   m: a mesh
%   mgens: an array of morphogen indexes or names.
%   multibrighten: a parameter affecting how colours are mixed.
%   mgenbound: Not sure what this does.  Never used.

    mvals = getEffectiveMgenLevels( m, mgens );
    
    c = combineColors( mvals, ...
            m.mgenposcolors(:,mgens), ...
            m.mgennegcolors(:,mgens), ...
            m.mgen_plotpriority(mgens), ...
            m.mgen_plotthreshold(mgens), ...
            multibrighten, ...
            mgenbound, ...
            m.plotdefaults.canvascolor );
end
