function h = plotmeshsurface( h, theaxes, s, vxs, polygons, data, pervertex, edgethickness, pointsize, params, userdata )
%h = plotmeshsurface( theaxes, s, vxs, polygons, data, pervertex, edgethickness, params, userdata )
%   Plot a polygon mesh.

    if isempty(vxs)
        return;
    end
    if pervertex
        if size( data, 1 ) ~= size(vxs,1)
            return;
        end
        facecolorinterpmode = 'interp';
    else
        if size( data, 1 ) ~= size(polygons,1) % length(visible.cells)
            return;
        end
        facecolorinterpmode = 'flat';
        % data = data( visible.cells==1, : );
    end

    [lw,ls,vw,vs] = basicLineStyle( edgethickness, pointsize );
    h = patchReuse( h, ...
            'Faces', polygons, ...
            'Vertices', vxs, ...
            'FaceVertexCData', data, ...
            'FaceColor', facecolorinterpmode, ...
            'LineWidth', lw, ...
            'LineStyle', ls, ...
            'Parent', theaxes, ...
            'ButtonDownFcn', @GFtboxGraphicClickHandler, ...
            'MarkerSize', vw, ...
            'Marker', vs, ...
            'UserData', userdata, ...
            params{:} );
end
