function h = plotmeshsurface( h, theaxes, s, vxs, polygons, data, pervertex, edgethickness, pointsize, params, userdata )
%h = plotmeshsurface( theaxes, s, vxs, polygons, data, pervertex, edgethickness, params, userdata )
%   Plot a polygon mesh.

    if isempty(vxs)
        return;
    end
    
    plotPerCorner = false;
    
    if pervertex
        if size( data, 1 ) ~= size(vxs,1)
            return;
        end
        facecolorinterpmode = 'interp';
    else
        if size( data, 1 ) == size(polygons,1) % length(visible.cells)
            facecolorinterpmode = 'flat';
        elseif size( data, 1 ) == numel(polygons)
            % Plot per corner.
            plotPerCorner = true;
        else
            return;
        end
    end
    
    [lw,ls,vw,vs] = basicLineStyle( edgethickness, pointsize );
    if plotPerCorner
        [oldvxindexes,splitfaces] = splitSharedVertexes( polygons );
        splitvxs = vxs( oldvxindexes, : );
        h = patchReuse( h, ...
                'Faces', splitfaces, ...
                'Vertices', splitvxs, ...
                'FaceVertexCData', data, ...
                'FaceColor', 'interp', ...
                'LineStyle', '-', ...
                'Marker', 'none', ...
                'LineWidth', lw, ...
                'LineStyle', ls, ...
                'Parent', theaxes, ...
                'ButtonDownFcn', @GFtboxGraphicClickHandler, ...
                'MarkerSize', vw, ...
                'Marker', vs, ...
                'UserData', userdata, ...
                 params{:} );
    else
        h = patchReuse( h, ...
                'Faces', polygons, ...
                'Vertices', vxs, ...
                'FaceVertexCData', data, ...
                'FaceColor', facecolorinterpmode, ...
                'LineWidth', lw, ...
                'LineStyle', ls, ...
                'Parent', theaxes, ...
                'ButtonDownFcn', @GFtboxGraphicClickHandler, ...
                'MarkerSize', vw, ...
                'Marker', vs, ...
                'UserData', userdata, ...
                params{:} );
    end
end
