function v = StandardPrism()
%v = StandardPrism()   Return the vertexes of a standard triangular prism.
    v = [ ...
            [ 0; 0; -1 ], ...
            [ 1; 0; -1 ], ...
            [ 0; 1; -1 ], ...
            [ 0; 0; 1 ], ...
            [ 1; 0; 1 ], ...
            [ 0; 1; 1 ], ...
        ];
end
