function g = smoothGrid( g, n )
    if nargin < 2, n = 1; end
    xn = size(g,1);
    yn = size(g,2);
    for i=1:n
        g = (g ...
            + g( [2:xn 1], :, : ) ...
            + g( [xn 1:(xn-1)], :, : ) ...
            + g( :, [2:yn 1], : ) ...
            + g( :, [yn 1:(yn-1)], : ))/5;
    end
end